import { createClient } from '@/lib/supabase/server';

export async function GET(): Promise<Response> {
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { data, error } = await supabase
    .from('recordings')
    .select('id, status, created_at, reports(id)')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })
    .limit(50);

  if (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }

  const recordings = (data ?? []).map((r) => ({
    id: r.id,
    status: r.status,
    created_at: r.created_at,
    has_report: Array.isArray(r.reports) ? r.reports.length > 0 : r.reports !== null,
  }));

  return Response.json({ recordings });
}

export async function POST(): Promise<Response> {
  const supabase = await createClient();

  // Verify the session — never trust client-supplied user IDs.
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Insert a new recordings row. The id is generated by Postgres.
  const { data, error: insertError } = await supabase
    .from('recordings')
    .insert({ user_id: user.id, storage_path: '', status: 'pending' })
    .select('id')
    .single();

  if (insertError || !data) {
    return Response.json(
      { error: 'Failed to create recording', detail: insertError?.message },
      { status: 500 }
    );
  }

  const recordingId: string = data.id;
  const storagePath = `${user.id}/${recordingId}.mp4`;

  // Now update the row with the correct storage_path derived from the id.
  const { error: updateError } = await supabase
    .from('recordings')
    .update({ storage_path: storagePath })
    .eq('id', recordingId);

  if (updateError) {
    return Response.json(
      { error: 'Failed to set storage path', detail: updateError.message },
      { status: 500 }
    );
  }

  return Response.json({ id: recordingId, storage_path: storagePath }, { status: 201 });
}
